### ISSUE TITLE
stuck in HAL_Delay after an arbitrary period of time

### ISSUE THREAD

**Issue by illidan1372** [leech001/SIM800MQTT#4]
hi.
thanks for creating this library , it saved me from having to manually create and send my own mqtt packets :D
i am using www.moqiatto.com to test your app. i am using a nucleo f446-re alongside a sim800l module to send mqtt packets.

i have started a fresh project to make sure that my firmware is not conflicting with your code , the problem is that when i set system clock on 80 MHZ(default) i receive messages from my micro with no problem however after some time i stop receiving messages when i set sys clock on 180mhz(max) i get stuck immidietaly before recieving anything..i though it was a server issue but when i debug your code manually by clicking on next step everything works fine but when everything happens automatically i get stuck in HAL_Delay. i think there is an interrupt conflict or something.
im using UART4
baud rate is 115200(maybe it's too high?)
NVIC priority for system clock is 0 and 0
NVIC priority for UART is also 0 , 0 changing it to 0 and 1 did not solve the issue.
can anyone help? thank you

**Comment by illidan1372** [comment]
checked again today , seems like it was a server issue because the problem got resolved today :D im still not sure what happened but well it is working today(tested with both moqiatto and hivemq)

**Comment by leech001** [comment]
Hi. I'm glad that everything is resolved for you. At the same time, the library is built on completely standard functions and I was very surprised by the problems with HAL_Delay. HAL_Delay is used only in the pause part so that the GPS module has time to respond.
If you have problems in the future you can replace it with any other implementation of the pause, starting from an empty loop and ending with a timer, for example DWT ([https://github.com/leech001/micros](https://github.com/leech001/micros))
